### ISSUE TITLE
AML crashes on launch

### ISSUE THREAD

**Issue by BDBrown314** [X2CommunityCore/xcom2-launcher#271]
When I start AML, it crashes immediately with the attached error.  It was working yesterday(28-Apr-21) and all I did today was re-arrange my desktop.

AML version: 1.4.1
Sentry GUID: a7b936e4-d2f4-4d71-947a-43f2a861684c
Message: Value cannot be null.
Parameter name: source

Stack: 
    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at XCOM2Launcher.Mod.ModList.GetRequiredMods(ModEntry mod, Boolean substituteDuplicates, Boolean checkIgnoredDependencies) in f:\AML\xcom2-launcher\xcom2-launcher\Classes\Mod\ModList.cs:line 668
   at XCOM2Launcher.Mod.ModList.UpdatedModDependencyState(ModEntry mod) in f:\AML\xcom2-launcher\xcom2-launcher\Classes\Mod\ModList.cs:line 116
   at XCOM2Launcher.Program.InitializeSettings() in f:\AML\xcom2-launcher\xcom2-launcher\Program.cs:line 395
   at XCOM2Launcher.Program.Main() in f:\AML\xcom2-launcher\xcom2-launcher\Program.cs:line 93
[AML.log](https://github.com/X2CommunityCore/xcom2-launcher/files/6402944/AML.log)
[settings.zip](https://github.com/X2CommunityCore/xcom2-launcher/files/6402955/settings.zip)
[settings.zip](https://github.com/X2CommunityCore/xcom2-launcher/files/6402959/settings.zip)

![image](https://user-images.githubusercontent.com/30243878/116647855-71efd700-a930-11eb-809e-23d985d6c2ea.png)

**Comment by RevZero** [comment]
We are aware of this problem #258. Its caused by a Steam Workshop request failing.
* It may have been a temporary issue, so please report back if it still persists for you.
* Its possible that a mod author removed his mod (you are/were using) from the workshop. In this case it would be a permanent problem. However, this would only actually cause the reported error if the deleted mod is also a required dependency for some mod you are using.

**Comment by BDBrown314** [comment]
Thank you for the response.  It is working now.
