### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Crysis123467** [X2CommunityCore/xcom2-launcher#336]
**AML Version:** 

AML version: 1.5.0
Sentry GUID: 9e4dca05-f254-419f-9200-a920d3422ef5
Message: One or more errors occurred.

Stack: 
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at XCOM2Launcher.Mod.ModEntry.GetUIScreenListenerOverrides() in f:\AML\xcom2-launcher\xcom2-launcher\Classes\Mod\ModEntry.cs:line 266
   at XCOM2Launcher.Forms.MainForm.UpdateConflictInfo() in f:\AML\xcom2-launcher\xcom2-launcher\Forms\MainForm.cs:line 505
   at XCOM2Launcher.Forms.MainForm.UpdateInterface() in f:\AML\xcom2-launcher\xcom2-launcher\Forms\MainForm.cs:line 461
   at XCOM2Launcher.Forms.MainForm..ctor(Settings settings) in f:\AML\xcom2-launcher\xcom2-launcher\Forms\MainForm.cs:line 49
   at XCOM2Launcher.Program.Main() in f:\AML\xcom2-launcher\xcom2-launcher\Program.cs:line 137

**Comment by RevZero** [comment]
See discussion #337
