### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by ManweTheValar** [X2CommunityCore/xcom2-launcher#391]
AML version: 1.5.1
Sentry GUID: 0cfeb511-e589-4453-8040-c47cf114dcc1
Message: Access to the path 'C:\Program Files (x86)\Steam\steamapps\workshop\content\268500\2668955805\Src\RetrieveItemsFromFallen\Classes' is denied.

Stack: 
    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at XCOM2Launcher.Mod.ModEntry.GetUIScreenListenerOverrides() in D:\AML\xcom2-launcher\xcom2-launcher\Classes\Mod\ModEntry.cs:line 227
   at XCOM2Launcher.Forms.MainForm.UpdateConflictInfo() in D:\AML\xcom2-launcher\xcom2-launcher\Forms\MainForm.cs:line 505
   at XCOM2Launcher.Forms.MainForm.UpdateInterface() in D:\AML\xcom2-launcher\xcom2-launcher\Forms\MainForm.cs:line 461
   at XCOM2Launcher.Forms.MainForm..ctor(Settings settings) in D:\AML\xcom2-launcher\xcom2-launcher\Forms\MainForm.cs:line 49
   at XCOM2Launcher.Program.Main() in D:\AML\xcom2-launcher\xcom2-launcher\Program.cs:line 137

**Comment by Dragon-32** [comment]
Check the permissions on that Classes folder
https://www.thewindowsclub.com/change-files-and-folders-permissions-in-windows-10

Your disks not nearly full is it?

Maybe try the 1.6 beta too.
