### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by AlbinoBlacky** [X2CommunityCore/xcom2-launcher#4]
Hi, I'm getting these errors on startup:

The given key was not present in the dictionary.
Stack:
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at XCOM2Launcher.Mod.ModInfo.LoadFile(String filepath)
   at XCOM2Launcher.Mod.ModList.Import(String modDir, ModSource source)
   at XCOM2Launcher.Mod.ModList.ImportMods(String dir)
   at XCOM2Launcher.Settings.ImportMods()
   at XCOM2Launcher.Program.InitializeSettings()
   at XCOM2Launcher.Program.Main()

I tried to repopulate the config folder by deleting and starting with no mods activate but this still occurs. Started happening since the last 22mb patch for xcom 2.

**Comment by BTernaryTau** [comment]
It looks like one of your mods is missing the "title" field in its XComMod file. I'll try to get a fix for the crash out soon.

**Comment by BTernaryTau** [comment]
Version 1.1.1 should no longer have this issue. Please let me know if it works for you.

**Comment by AlbinoBlacky** [comment]
Hi,

Thank you so much. Latest release did the trick. It seems that one of my none steam mods was causing the issue with the title being blank. Thank you again for the quick fix, I wasn't expecting it to be real fast :+1:
