### ISSUE TITLE
Crash on startup due to exception

### ISSUE THREAD

**Issue by Izicata** [X2CommunityCore/xcom2-launcher#40]
The program fails to launch, throwing up an error dialogue box that says: "An exception occured. See error.log for details."

The contents of error.log are:

>Method not found: 'System.DateTimeOffset System.DateTimeOffset.FromUnixTimeSeconds(Int64)'.
>Stack:
>  at XCOM2Launcher.Program.CheckDotNet4_6()
>  at XCOM2Launcher.Program.Main()

Running on Windows 7.

**Comment by Izicata** [comment]
I rechecked the requirements and I only have .NET 4.5.2, not 4.6. My mistake.
