### ISSUE TITLE
Access to PerfLogs is denied.

### ISSUE THREAD

**Issue by grimdour** [X2CommunityCore/xcom2-launcher#8]
Access to the path 'C:\PerfLogs' is denied.
Stack:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at XCOM2Launcher.Mod.ModList.Import(String modDir, ModSource source)
   at XCOM2Launcher.Mod.ModList.ImportMods(String dir)
   at XCOM2Launcher.Settings.ImportMods()
   at XCOM2Launcher.Program.InitializeSettings()
   at XCOM2Launcher.Program.Main()

**Comment by BTernaryTau** [comment]
Can you give me a copy of your settings.json please?

**Comment by grimdour** [comment]
I don't actually have that file. I'm guessing I should.

**Comment by BTernaryTau** [comment]
In that case, are you using version 1.1.2? If so, try reverting to 1.1.1 and see if that fixes it.

**Comment by RevZero** [comment]
Access problem to system folder `C:\PerfLogs` that was potentially specified as a mod folder. Newer versions handle this without crashing. The issue relates to a very old version of AML.
